// Generated by CoffeeScript 1.6.3
(function() {
  var Wallet;

  Wallet = require("../models/wallet");

  module.exports = function(app) {
    app.get("/", function(req, res) {
      return res.render("site/index", {
        title: 'Home',
        user: req.user
      });
    });
    app.get("/trade", function(req, res) {
      return res.render("site/trade", {
        title: 'Trade',
        user: req.user
      });
    });
    app.get("/funds", function(req, res) {
      return res.render("site/funds", {
        title: 'Funds',
        user: req.user,
        currencies: Wallet.getCurrencies()
      });
    });
    return app.get("/settings", function(req, res) {
      return res.render("site/settings", {
        title: 'Settings',
        user: req.user
      });
    });
  };

}).call(this);
