// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(app) {
    app.get("/", function(req, res) {
      return res.render("site/index", {
        user: req.user
      });
    });
    return app.get("/signup", function(req, res) {
      return res.render("site/signup");
    });
  };

}).call(this);
