// Generated by CoffeeScript 1.6.3
(function() {
  var JsonRenderer, User;

  User = require('../models/user');

  JsonRenderer = require('../lib/json_renderer');

  module.exports = function(app) {
    app.post("/user", function(req, res) {
      var user;
      user = new User({
        email: req.body.email,
        password: req.body.password
      });
      return user.save(function(err) {
        if (err) {
          console.error("Could not create user", err);
          res.statusCode = 409;
          return res.json({
            "error": "User cannot be created"
          });
        } else {
          return res.json(JsonRenderer.user(user));
        }
      });
    });
    app.post("/login", passport.authenticate("local"), function(req, res) {
      return res.json(JsonRenderer.user(req.user));
    });
    app.put("/login", passport.authenticate("local"), function(req, res) {
      return res.json(JsonRenderer.user(req.user));
    });
    app.get("/user/:id?", function(req, res) {
      if (!req.user) {
        res.statusCode = 409;
        return {};
      }
      return res.json(JsonRenderer.user(req.user));
    });
    return app.get("/logout", function(req, res) {
      req.logout();
      return res.json({});
    });
  };

}).call(this);
